version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_server
    ports:
      - 5000:5000
    volumes:
      - '.:/app'
  
  mysql_server:
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
     - MYSQL_DATABASE=theorem
     - MYSQL_ROOT_PASSWORD=root
    volumes: 
      - mysql_server:/var/lib/mysql

volumes:
  mysql_server:
    driver: local