version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT    
    volumes: 
      - db:/var/lib/mysql
  api:
    container_name: smartac_api
    build:
      context: .
    image: api
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_DOCKER_PORT
    links:
      - db
    volumes:
      - './:/src'
volumes:
  db:
    driver: local